version: "3.9"

services:
  app:
    build: .
    container_name: goit_final_app
    ports:
      - "3000:3000"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "3000"
      SOCKET_HOST: "0.0.0.0"
      SOCKET_PORT: "5000"
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "goit"
      MONGO_COLLECTION: "messages"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: goit_final_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
